### PR TITLE
Backport JEI integration for Bulk Filter (mainly for VH)

### PR DESCRIPTION
**Pull request by Attack8**

### CODE REVIEW

**Comment by desht** [comment]
Merged, thanks!

**Comment by Attack8** [comment]
Is this release (9.1.3) going to get released? I see that you have updated the changelog and such, but it is not on cf. Thanks!

**Comment by Attack8** [comment]
@desht

**Comment by desht** [comment]
Yeah I'll see if I can get a release done this week

**Comment by Attack8** [comment]
Great, thanks!

**Pull request merged**
