### PR TITLE
update zh_cn

### PR DESCRIPTION
**Pull request by a5161655**

### CODE REVIEW

**Comment by desht** [comment]
Merged, thanks!

**Comment by desht** [comment]
I noticed two lines that still need a translation, if you wouldn't mind:
```
  "itemText.misc.holdShiftKey": "§7§o▶ Hold §3§o[Shift]§7§o for settings, §3§o[%s]§7§o for more info",
  "itemText.misc.holdKey": "§7§o▶ Hold §3§o[%s]§7§o for more info"
```

**Comment by a5161655** [comment]
"itemText.misc.holdShiftKey": "§7§o▶ 按住 §3§o[Shift]§7§o 显示设置, §3§o[%s]§7§o 了解更多信息",
  "itemText.misc.holdKey": "§7§o▶ 按住 §3§o[%s]§7§o 了解更多信息"

**Comment by a5161655** [comment]
emm,I don't know why the ▶ change to emoji automatic

**Pull request merged**
